name: CI/CD - Deploy to Development
  
on: 
  push:
    branches: 
      - dev_cpcloud     # Trigger on push to dev_cpcloud
  pull_request:
    branches:
      - dev_cpcloud     # Trigger on PR against dev_cpcloud

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Deploy to Development
      uses: easingthemes/ssh-deploy@v5.1.0
      with:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        script: cd /var/www/dev.cpcloud.in/public_html && git pull origin dev_cpcloud
