name: WordPress Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.YOUR_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy WordPress
        run: |
          scp -o StrictHostKeyChecking=no -r . ${{ secrets.YOUR_SSH_USER }}@${{ secrets.YOUR_SERVER_IP }}:/var/www/dev.cpcloud.in/public_html
